MODULE interface

        IMPLICIT NONE

        INTEGER, PARAMETER :: NGRID = 158      !       NGRID X NGRID FOR BRILLOUIN ZONE
        INTEGER, PARAMETER :: NGRID2 = NGRID/2
        INTEGER, PARAMETER :: NPOINTS = (NGRID-1)*(NGRID-1)+2*(NGRID-1) + 1 !       # OF POINTS IN BZ

        REAL (KIND=8), PARAMETER :: AN = 0.35D0   !       DEFINES DOPPING (4 + AN)
        REAL (KIND=8) :: AMU          !       CHEMICAL POTENTIAL 

        REAL (KIND=8), PARAMETER :: ETA = 0.005d0!1.D-2
        REAL (KIND=8), PARAMETER :: TEMP = 0.0001!1.D-4

        INTEGER, PARAMETER :: NORBIT = 5             !       NUMBER OF ORBITALS IN EACH SITE
        INTEGER, PARAMETER :: NNX = 2             !       NUMBER OF NEIGBORS IN THE X DIRECTION
        INTEGER, PARAMETER :: NNY = 2             !       NUMBER OF NEIGBORS IN THE Y DIRECTION
        REAL (KIND=8), PARAMETER  :: PI = DACOS(-1.d0)                         !    3.1415...

        REAL (KIND=8), DIMENSION(-NNX:NNX,-NNY:NNY,NORBIT,NORBIT) :: HOPIJ        !       INTRAORBITAL HOPPINGS
        REAL (KIND=8), DIMENSION(NORBIT) :: ENER    !       EIGENVALUES
        REAL (KIND=8), DIMENSION(NORBIT,NORBIT) :: VECR  !       EIGENVECTORS (REAL PART)
        REAL (KIND=8), DIMENSION(NORBIT,NORBIT) :: VECI  !       EIGENVECTORS (IMAGINARY PART)

END MODULE interface
