PROGRAM CHEMPOT
	
	USE INTERFACE

	IMPLICIT NONE
	
	INTEGER, DIMENSION(NORBIT,NORBIT) :: INDEX
	
	REAL (KIND=8), PARAMETER :: MUCONV=1.d-9
	REAL (KIND=8) :: BETA
	REAL (KIND=8) :: MU       !       CHEMICAL POTENTIAL CONVERGED
	
	INTEGER :: I1,I2,I3,I4,I5,I             !       DO LOOP COUNTERS
	INTEGER :: K1,K2             !       DO LOOP COUNTERS
	INTEGER :: KX,KY,IR1,IR2
	
	REAL (KIND=8), DIMENSION(-NGRID2:NGRID2) :: A1024_1024    ! AUXILIARY
	REAL (KIND=8), DIMENSION(NORBIT,-NGRID2:NGRID2,-NGRID2:NGRID2) :: EK       !       EIGENVALUES AT WAVE VECTOR K 
	REAL (KIND=8), DIMENSION(-NGRID2:NGRID2) :: AKX       !       WAVE VECTOR IN THE X DIRECTION
    REAL (KIND=8), DIMENSION(-NGRID2:NGRID2) :: AKY       !       WAVE VECTOR IN THE Y DIRECTION
    REAL (KIND=8) :: DKX,DKY
    
    REAL (KIND=8) :: MINENERGY       !       MINIMAL VALUE OF EIGENVALUES
    REAL (KIND=8) :: MAXENERGY       !       MAXIMAL VALUE OF EIGENVALUES
    INTEGER :: NSTEPS       !       STEPS IN ENERGY RANGE
    INTEGER(8), PARAMETER :: NNUM=60*(NPOINTS)
    REAL (KIND=8), DIMENSION(0:NNUM) :: EVAR       !       AUXILIARY ENERGY VARIABLE
    COMPLEX (KIND=8) :: G       !       GREEN FUNCTION
    REAL (KIND=8), DIMENSION(0:NNUM) :: RHO       !       DOS
    REAL(8), DIMENSION(0:NNUM) :: INTEGRAL
    INTEGER, PARAMETER :: numsize = 10
    REAL (KIND=8), DIMENSION(0:numsize) :: LISTNE
    REAL (KIND=8) :: NE
    
    REAL (KIND=8) :: EF       !       FERMI ENERGY
    REAL (KIND=8) :: MUMIN       !       LOWER CHEMICAL POTENTIAL
    REAL (KIND=8) :: MUCEN       !       CENTRAL CHEMICAL POTENTIAL
    REAL (KIND=8) :: MUMAX       !       UPPER CHEMICAL POTENTIAL
    REAL (KIND=8) :: FMIN       !       LOWER FERMI FUNCTION
    REAL (KIND=8) :: FCEN       !       CENTER FERMI FUNCTION
    REAL (KIND=8) :: FMAX       !       UPPER FERMI FUNCTION
    REAL (KIND=8) :: FF       !       AUXILIARY FUNCTION
    
	BETA = 1.d0/(8.617D-5*TEMP)
	
!	WRITE THE NUMBER ELECTRONS RANGE

	DO I1 = 0, numsize
		LISTNE(I1)= 4.35D0 + I1*0.01D0 ! AQUI É A PARTE IMPORTANTE, PONTO INCIAL + INDEX * STEP
	END DO
	
!	READ THE INPUT FILE

	OPEN(UNIT=1,FILE='input-ws.dat',STATUS='UNKNOWN')

	DO KX = -NNX, NNX
		DO KY = -NNY, NNY
			READ(1,*)IR1,IR2
			DO I1 = 1, NORBIT
				READ(1,*)(HOPIJ(IR1,IR2,I1,I2),I2=1, NORBIT) 
            END DO
		END DO
	END DO

	CLOSE(1)
	DO KX = -NNX, NNX
		DO KY = -NNY, NNY
			DO I1 = 1, NORBIT
				print*,(HOPIJ(kx,ky,I1,I2),I2=1, NORBIT) 
            END DO
		END DO
	END DO
	stop
	A1024_1024  = (/ (DBLE(I), I = -NGRID2, NGRID2)  /)
	
!   WAVE VECTORS FOR THE GRID

	AKX(-NGRID2:NGRID2) = A1024_1024(-NGRID2:NGRID2) * PI/DBLE(NGRID2)

    AKY(-NGRID2:NGRID2) = AKX(-NGRID2:NGRID2)
    
!   TRANSLATION FROM ONE BASIS TO ANOTHER

	DO K1 = 1, NORBIT
		DO K2 = 1, NORBIT
			INDEX(K1,K2) = (K1-1)*NORBIT + K2
		END DO
	END DO

!	HERE WE CALCULATE THE BAND STRUCTURE IN THE GRID AND STORE THE EIGENVALUES

	DO I3 = -NGRID2, NGRID2         !       KY IN THE GRID
		DO I4 = -NGRID2, NGRID2     !       KX IN THE GRID
			DKX = AKX(I4)
			DKY = AKY(I3)

			CALL TIGHTB(DKX,DKY)

			DO K1 = 1, NORBIT
				EK(K1,I4,I3) = ENER(K1)
			END DO 		
						
		END DO						!       END KX IN THE GRID						
	END DO							!       END KY IN THE GRID
	
	MINENERGY = MINVAL(EK)
	MAXENERGY = MAXVAL(EK)
	NSTEPS = INT(((MAXENERGY+0.5d0)-(MINENERGY-0.5d0))/val_step_energy)

!	DOS: VIA GREEN'S FUNCTION
						
	DO I5=0,NSTEPS
		EVAR(I5)=MINENERGY-0.5d0 + I5*val_step_energy
		G=DCMPLX(0.d0,0.d0)
		DO I3 = -NGRID2, NGRID2         !       KY IN THE GRID
			DO I4 = -NGRID2, NGRID2     !       KX IN THE GRID
				DO K1 = 1, NORBIT
					G=G+1/(EVAR(I5)+DELTA-EK(K1,I4,I3)) 
				END DO
				
			END DO
		END DO
		
		RHO(I5)=-DIMAG(G)/(NPOINTS*PI) 
	END DO	
		
!	LOOP WITH ALL VALUES IN LISTNE

	DO I2=0, numsize
		NE = LISTNE(I2)/2.d0
						
!	CALCULATING RHO INTEGRAL AND ESTIMATING EF

		INTEGRAL = 0.d0
		DO I5=1,NSTEPS-1
			INTEGRAL(I5) = INTEGRAL(I5-1) + (RHO(I5)+RHO(I5+1))
		END DO
		INTEGRAL=INTEGRAL*val_step_energy/2.d0
	
!	SAVING THE DOS, THE RANGE OF ENERGY AND THE INTEGRAL VALUES
	
	!OPEN(UNIT=1,FILE='DOS.dat')
	!	DO I5=0,NSTEPS
	!		WRITE(1,*) EVAR(I5), RHO(I5), INTEGRAL(I5)
	!	ENDDO
	!CLOSE(1)

!	DEFINE THE EF:
		DO I5=0,NSTEPS
			IF (INTEGRAL(I5)>=NE) THEN
				EXIT
			END IF
		END DO

		IF (INTEGRAL(I5)==NE) THEN
			EF=EVAR(I5)
		ELSE
			EF=EVAR(I5-1)+val_step_energy*(NE-INTEGRAL(I5-1))/                       &
				&(INTEGRAL(I5)-INTEGRAL(I5-1))
		END IF

!	STARTING MU CALCULATION

		MUMAX = EF+0.5D0
		MUMIN = EF-0.5D0
		MUCEN = EF
		FMAX = 0.D0
		FMIN = 0.D0
		
		DO I3 = -NGRID2, NGRID2         !       KY IN THE GRID
			DO I4 = -NGRID2, NGRID2     !       KX IN THE GRID
				DO K1 = 1, NORBIT
					FMAX = FMAX + 1.D0/(DEXP(BETA*(EK(K1,I4,I3)-MUMAX)) + 1.D0) 
					FMIN = FMIN + 1.D0/(DEXP(BETA*(EK(K1,I4,I3)-MUMIN)) + 1.D0)
				END DO
					
			END DO
		END DO
		
		FMAX = (FMAX/REAL(NPOINTS))-NE
		FMIN = (FMIN/REAL(NPOINTS))-NE
		FF = FMAX*FMIN
		
		IF (ff>0) THEN
			PRINT*,'PROBLEM IN MU_EVAL: ff IS POSITIVE'
			STOP
		END IF
		
		DO WHILE (DABS(MUMAX-MUMIN)>MUCONV)
		
			FCEN = 0.D0
			FMIN = 0.D0
			MUCEN = 0.5D0*(MUMAX+MUMIN)
			
			DO I3 = -NGRID2, NGRID2         !       KY IN THE GRID
				DO I4 = -NGRID2, NGRID2     !       KX IN THE GRID
					DO K1 = 1, NORBIT
						FCEN = FCEN + 1.D0/(DEXP(BETA*(EK(K1,I4,I3)-MUCEN)) + 1.D0) 
						FMIN = FMIN + 1.D0/(DEXP(BETA*(EK(K1,I4,I3)-MUMIN)) + 1.D0)
					END DO
						
				END DO
			END DO
			
			FCEN = (FCEN/REAL(NPOINTS))-NE
			FMIN = (FMIN/REAL(NPOINTS))-NE
			FF = FCEN*FMIN
			
			IF (FF<0) THEN
				MUMAX=MUCEN
			ELSE
				MUMIN=MUCEN
			END IF
		
		END DO		!		END WHILE
		
		MU=0.5d0*(MUMAX+MUMIN)
		PRINT*, 'MU=', MU
	
!	SAVING THE MU
	
		!OPEN(UNIT=1,FILE='MU.dat', ACCESS = 'APPEND',STATUS='UNKNOWN')
		!	WRITE(1,*) NE, NE*2.d0, 2.d0*NE-4.d0, MU
		!CLOSE(1)
		
	END DO		!	END DO OF NUMBER OF ELECTRONS
	
END PROGRAM CHEMPOT
