MODULE interface

        IMPLICIT NONE

        INTEGER, PARAMETER :: NORBIT = 5             !       NUMBER OF ORBITALS IN EACH SITE
        INTEGER, PARAMETER :: NORBIT2 = NORBIT*NORBIT

        INTEGER, PARAMETER :: NGRID = 158
        INTEGER, PARAMETER :: NGRID2 = NGRID/2

        INTEGER, PARAMETER :: NPSURF = 27                     !   NUMBER OF POINTS IN EACH POCKET - 1
        INTEGER, PARAMETER :: NTOT = NPSURF + 1                     !   NUMBER OF POINTS IN EACH POCKET

        INTEGER, PARAMETER :: IFLAG = 1               !       0 -> DOES NOT CALCULATE EIGENVECTORS 1 -> DOES
        INTEGER, PARAMETER :: IVEC = 1               !       WHAT GAP FUNCTION SHOULD BE USED FOR PAIRING STRENGTH
        INTEGER, PARAMETER :: IDOP = 35               !       DEFINES DOPING LEVEL: 35(n = 4.35)
        INTEGER, PARAMETER :: NPOC = 7                     !   NUMBER OF POCKETS
        INTEGER, PARAMETER :: NITER = 1               !       # OF DIFFERENT VALUES OF U 
        INTEGER, PARAMETER :: NTOT2 = NPOC*NTOT            !   TOTAL NUMBER OF POINTS


        REAL (KIND=8), PARAMETER  :: PI = DACOS(-1.D0)                         !    3.1415...

        REAL (KIND=8), PARAMETER :: ETA = 1.D-5
        REAL (KIND=8), PARAMETER :: TEMP = 1.D-4
        REAL (KIND=8), PARAMETER :: TOL = 1.D-20
        REAL (KIND=8), PARAMETER :: DELTAFI = 2.D0 * PI / DBLE(NTOT)
        REAL (KIND=8), PARAMETER :: AKXCELL = PI/DBLE(NGRID2)
        REAL (KIND=8), PARAMETER :: AKYCELL = PI/DBLE(NGRID2)

        REAL (KIND=8), PARAMETER :: ALFA = 0.25D0
        REAL (KIND=8), PARAMETER :: AUINIT = 0.51D0
        REAL (KIND=8), PARAMETER :: AUINTER = 0.06D0

        REAL (KIND=8), DIMENSION(-NGRID2:NGRID2) :: AKX       !       WAVE VECTOR IN THE X DIRECTION
        REAL (KIND=8), DIMENSION(-NGRID2:NGRID2) :: AKY       !       WAVE VECTOR IN THE Y DIRECTION
        REAL (KIND=8), DIMENSION(0:NPSURF) :: PHI       !       ANGLE AROUND THE FERMI SURFACE
        REAL (KIND=8), DIMENSION(NPOC,2,0:NPSURF) :: AK       !       K VECTORS FOR ALL POCKETS
        REAL (KIND=8), DIMENSION(NPOC,0:NPSURF) :: PHIREAD       !       ANGLE AROUND THE FERMI SURFACE
        REAL (KIND=8), DIMENSION(NPOC,0:NPSURF) :: VFERMI   !       FERMI VELOCITIES
        
        REAL (KIND=8), DIMENSION(NORBIT2,NORBIT2) :: UC       !       INTERACTION MATRIX FOR CHARGE
        REAL (KIND=8), DIMENSION(NORBIT2,NORBIT2) :: US       !       INTERACTION MATRIX FOR SPIN
        REAL (KIND=8), DIMENSION(NITER) :: AU       !       HUBBARD U (GRASER'S NOTATION)
        REAL (KIND=8), DIMENSION(NITER) :: AV       !       NNN COULOMB (GRASER'S NOTATION)
        REAL (KIND=8), DIMENSION(NITER) :: AJ       !       HUND�S COUPLING (GRASER'S NOTATION)
        REAL (KIND=8), DIMENSION(NITER) :: AJP       !       PAIR HOPPING (GRASER'S NOTATION)
        REAL (KIND=8), DIMENSION(NITER) :: AUK       !       HUBBARD U (KUBO NOTATION)
        REAL (KIND=8), DIMENSION(NITER) :: AVK       !       NNN COULOMB (KUBO NOTATION)
        REAL (KIND=8), DIMENSION(NITER) :: AJK       !       HUND�S COUPLING (KUBO NOTATION)
        REAL (KIND=8), DIMENSION(NITER) :: AJPK       !       PAIR HOPPING (KUBO NOTATION)

END MODULE interface
