PROGRAM PATH

	USE INTERFACE

	IMPLICIT NONE
	
	INTEGER, DIMENSION(NORBIT,NORBIT) :: INDEX
	
	INTEGER :: I1,I2,I3,I4,I5,I6,I             !       DO LOOP COUNTERS
	INTEGER :: K1,K2             !       DO LOOP COUNTERS
	INTEGER :: KX,KY,IR1,IR2
	
	REAL (KIND=8), DIMENSION(-NGRID2:NGRID2) :: A1024_1024    ! AUXILIARY
	REAL (KIND=8), DIMENSION(NORBIT,-NGRID2:NGRID2,-NGRID2:NGRID2) :: EK       !       EIGENVALUES AT WAVE VECTOR K 
	REAL (KIND=8), DIMENSION(NORBIT,0:NGRID2) :: EK1       !       EIGENVALUES AT WAVE VECTOR K IN REGION 1 
	REAL (KIND=8), DIMENSION(NORBIT,0:NGRID2) :: EK2       !       EIGENVALUES AT WAVE VECTOR K IN REGION 2 
	REAL (KIND=8), DIMENSION(NORBIT,0:NGRID2) :: EK3       !       EIGENVALUES AT WAVE VECTOR K IN REGION 3 
	REAL (KIND=8), DIMENSION(NORBIT,0:NGRID2) :: EK3T       !       EIGENVALUES AT WAVE VECTOR K IN REGION 3 
	REAL (KIND=8), DIMENSION(NORBIT,0:INT(3*5*NGRID2+2)) :: EKT
	INTEGER :: COUNTER
	INTEGER :: AUXCOUNTER
	REAL (KIND=8), DIMENSION(-NGRID2:NGRID2) :: AKX       !       WAVE VECTOR IN THE X DIRECTION
    REAL (KIND=8), DIMENSION(-NGRID2:NGRID2) :: AKY       !       WAVE VECTOR IN THE Y DIRECTION
    REAL (KIND=8) :: DKX,DKY
    
    REAL (KIND=8), DIMENSION(1:3) :: EKMIN
    REAL (KIND=8), DIMENSION(1:3) :: EKMAX
    REAL (KIND=8) :: MINENERGY       !       MINIMAL VALUE OF EIGENVALUES
    REAL (KIND=8) :: MAXENERGY       !       MAXIMAL VALUE OF EIGENVALUES
    INTEGER :: NSTEPS       !       STEPS IN ENERGY RANGE
    INTEGER(8), PARAMETER :: NNUM=50*(3*NPOINTS)
    REAL (KIND=8), DIMENSION(0:NNUM) :: EVAR       !       AUXILIARY ENERGY VARIABLE
    COMPLEX (KIND=8) :: G       !       GREEN FUNCTION
    REAL (KIND=8), DIMENSION(0:NNUM) :: RHO       !       DOS
    
!	READ THE CHEMICAL POTENTIAL CALCULATED BY CHEMPOT.F90 (HENRI)
	
	OPEN(UNIT=1,FILE='MU.dat',STATUS='UNKNOWN')

	READ(1,*)AMU

	CLOSE(1)

!	READ THE INPUT FILE
	 
    OPEN(UNIT=1,FILE='input-ws.dat',STATUS='UNKNOWN')

	DO KX = -NNX, NNX
		DO KY = -NNY, NNY
			READ(1,*)IR1,IR2
			DO I1 = 1, NORBIT
				READ(1,*)(HOPIJ(IR1,IR2,I1,I2),I2=1, NORBIT) 
            END DO
		END DO
	END DO

	CLOSE(1)

	A1024_1024  = (/ (DBLE(I), I = -NGRID2, NGRID2)  /)
	
!   WAVE VECTORS FOR THE GRID

	AKX(-NGRID2:NGRID2) = A1024_1024(-NGRID2:NGRID2) * PI/DBLE(NGRID2)

    AKY(-NGRID2:NGRID2) = AKX(-NGRID2:NGRID2)
    
!   TRANSLATION FROM ONE BASIS TO ANOTHER

	DO K1 = 1, NORBIT
		DO K2 = 1, NORBIT
			INDEX(K1,K2) = (K1-1)*NORBIT + K2
		END DO
	END DO

!	HERE WE CALCULATE THE BAND STRUCTURE IN THE PATH GAMMA-X-M-GAMMA AND STORE THE EIGENVALUES

!	GAMMA TO X

	DO I3 = 0, NGRID2         !       KY IN THE GRID
		I4 = 0     !       KX IN THE GRID
		DKX = AKX(I4)
		DKY = AKY(I3)

		CALL TIGHTB(DKX,DKY)

			DO K1 = 1, NORBIT
				EK1(K1,I3) = ENER(K1)
			END DO 		
																		
	END DO							!       END KY IN THE GRID
	
!	SAVING EIGENVALUES IN THE REGION 1
	
	OPEN(UNIT=1,FILE='R1.txt')
		DO I3 = 0, NGRID2
			WRITE(1,*) EK1(1,I3), EK1(2,I3), EK1(3,I3), EK1(4,I3), EK1(5,I3)
		ENDDO
	CLOSE(1)

!	X TO M

	DO I4 = 0, NGRID2         !       KX IN THE GRID
		I3 = NGRID2     !       KY IN THE GRID
		DKX = AKX(I4)
		DKY = AKY(I3)

		CALL TIGHTB(DKX,DKY)

			DO K1 = 1, NORBIT
				EK2(K1,I4) = ENER(K1)
			END DO 		
																		
	END DO							!       END KX IN THE GRID
	
!	SAVING EIGENVALUES IN THE REGION 2
	
	OPEN(UNIT=1,FILE='R2.txt')
		DO I4 = 0, NGRID2
			WRITE(1,*) EK2(1,I4), EK2(2,I4), EK2(3,I4), EK2(4,I4), EK2(5,I4)
		ENDDO
	CLOSE(1)
	
!	M TO GAMMA

	DO I6 = 0, NGRID2    
	    I4 = I6     !       KX IN THE GRID
		I3 = I6     !       KY IN THE GRID
		DKX = AKX(I4)
		DKY = AKY(I3)

		CALL TIGHTB(DKX,DKY)

			DO K1 = 1, NORBIT
				EK3(K1,I6) = ENER(K1)
			END DO 		
																		
	END DO							!       END KX AND KY IN THE GRID
	
!	SAVING EIGENVALUES IN THE REGION 3
	
	OPEN(UNIT=1,FILE='R3.txt')
		DO I6 = 0, NGRID2
			WRITE(1,*) EK3(1,I6), EK3(2,I6), EK3(3,I6), EK3(4,I6), EK3(5,I6)
		ENDDO
	CLOSE(1)
	
	DO I6 = 0, NGRID2
		DO K1 = 1, NORBIT
			EK3T(K1, NGRID2-I6) = EK3(K1,I6)
		END DO
	END DO
	
!	WRITE IN UNIQUE ARRAY	
	COUNTER = 0
	DO I6 = 0, NGRID2
		DO K1 = 1, NORBIT
			EKT(K1, I6) = EK1(K1,I6)
			COUNTER = COUNTER + 1
		END DO
	END DO
	
	AUXCOUNTER = COUNTER

	DO I6 = AUXCOUNTER, INT(NGRID2+AUXCOUNTER)
		DO K1 = 1, NORBIT
			I5 = INT(I6-AUXCOUNTER)
			EKT(K1, I6) = EK2(K1,I5)
			COUNTER = COUNTER + 1
		END DO
	END DO

	AUXCOUNTER = COUNTER

	DO I6 = AUXCOUNTER, INT(NGRID2+AUXCOUNTER)
		DO K1 = 1, NORBIT
			I5 = INT(I6-AUXCOUNTER)
			EKT(K1, I6) = EK3T(K1,I5)
			COUNTER = COUNTER + 1
		END DO
	END DO
!	SAVING EIGENVALUES 
	
	!OPEN(UNIT=1,FILE='RT.txt')
	!	DO I6 = 0, INT(3*NGRID2+2)
	!		WRITE(1,*) EKT(1,I6), EKT(2,I6), EKT(3,I6), EKT(4,I6), EKT(5,I6)
	!	ENDDO
	!CLOSE(1)

	EKMIN(1) = MINVAL(EK1)
	EKMIN(2) = MINVAL(EK2)
	EKMIN(3) = MINVAL(EK3)
	EKMAX(1) = MAXVAL(EK1)
	EKMAX(2) = MAXVAL(EK2)
	EKMAX(3) = MAXVAL(EK3)
	
	MINENERGY = MINVAL(EKMIN)
	MAXENERGY = MINVAL(EKMAX)
	NSTEPS = INT(((MAXENERGY+0.5d0)-(MINENERGY-0.5d0))/val_step_energy)

!	HERE WE CALCULATE THE BAND STRUCTURE IN THE GRID AND STORE THE EIGENVALUES

	DO I3 = -NGRID2, NGRID2         !       KY IN THE GRID
		DO I4 = -NGRID2, NGRID2     !       KX IN THE GRID
			DKX = AKX(I4)
			DKY = AKY(I3)

			CALL TIGHTB(DKX,DKY)

			DO K1 = 1, NORBIT
				EK(K1,I4,I3) = ENER(K1)
			END DO 		
						
		END DO						!       END KX IN THE GRID						
	END DO							!       END KY IN THE GRID
	
	MINENERGY = MINVAL(EK)
	MAXENERGY = MAXVAL(EK)
	NSTEPS = INT(((MAXENERGY+0.5d0)-(MINENERGY-0.5d0))/val_step_energy)

!	DOS: VIA GREEN'S FUNCTION
						
	DO I5=0,NSTEPS
		EVAR(I5)=MINENERGY-0.5d0 + I5*val_step_energy
		G=DCMPLX(0.d0,0.d0)
		DO I3 = -NGRID2, NGRID2         !       KY IN THE GRID
			DO I4 = -NGRID2, NGRID2     !       KX IN THE GRID
				DO K1 = 1, NORBIT
					G=G+1/(EVAR(I5)+DELTA-EK(K1,I4,I3)) 
				END DO
				
			END DO
		END DO
		
		RHO(I5)=-DIMAG(G)/(NPOINTS*PI) 
	END DO	
						
	
!	SAVING THE DOS AND THE RANGE OF ENERGY
	
	OPEN(UNIT=1,FILE='DOS.dat')
		DO I5=0,NSTEPS
			WRITE(1,*) EVAR(I5), RHO(I5)
		ENDDO
	CLOSE(1)

END PROGRAM
